### ISSUE TITLE
Need to configure TravisCI 

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/gohive#2]
@yuyicg , could you please configure TravisCI? If there will be any technical challenge, please feel free to let @tonyyang-svail and I know.

**Comment by yuyicg** [comment]
already issued an application for adding the sql-machine-learning organization to the Travis-CI, there would be an email for @wangkuiyi to approval this application.

**Comment by tonyyang-svail** [comment]
@yuyicg Added sql-machine-learning organization to the Travis-CI.
