### ISSUE TITLE
Unify import path

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/gohive#55]
As https://github.com/sql-machine-learning/sqlflow/pull/908, we need to unify the import path in all the submodules, otherwise, there would be two repos like:

``` text
|-github.com
  `-sql-machin-learning
     `-gohive
`-sqlflow.org
    `-gohive
```

**Comment by tonyyang-svail** [comment]
Fixed by https://github.com/sql-machine-learning/gohive/pull/56.
